# Generated by Django 2.1.7 on 2019-03-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='fish_type',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
