# Generated by Django 2.1.7 on 2019-03-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_fish_fish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='fish_category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
