# Generated by Django 2.1.7 on 2019-03-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='no_of_years_in_fishery',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
